// src/ui/icons.ts — consumption helpers for the pre-rendered tank icons in
// public/icons/ (generated by `npm run tank:assets` from the shipped models;
// `npm run tank:release:check -- --ids=<id>` gates every tank landing):
//   <id>_angle.webp           3/4 hero  -> garage carousel cards
//   <id>_top.webp             top-down  -> tactical overlays
//   <id>_side.webp            side view -> detail panes
//   <id>_top_silhouette.png   flat white -> minimap blips (tinted green/red)
//   <id>_side_silhouette.png  flat white -> team panels, kill feed, damage panel
//   <id>_armor_side.png        effective-KE / penetration-information diagram
//   <id>_modules_side.png      actual module damage-volume diagram
//   <id>_crew_side.png         actual crew damage-volume diagram
// Silhouettes ship as white fills so one file serves every team color.
// perf-r3c (Lighthouse): shaded views ship as WebP q90 — the PNG set weighed
// 214-237 KB per 512px icon and dominated page transfer. Silhouettes stay
// PNG: they are tiny flat alpha masks, and Chrome's canvas WebP encoder is
// lossy-only (lossy alpha rings on mask edges).

/** URL of a generated icon. @param {string} id tank id @param {string} view e.g. 'angle' */
export const iconUrl = (id: string, view: string): string => `/icons/${id}_${view}.${
  /(?:silhouette|armor_side|modules_side|crew_side)$/.test(view) ? 'png' : 'webp'}`;

interface TintCacheEntry {
  canvas: HTMLCanvasElement | null;
}

const tintCache = new Map<string, TintCacheEntry>();

/**
 * Tinted silhouette as a canvas for per-frame 2D drawing (minimap blips).
 * Kicks off the image load on first request and returns null until ready —
 * callers draw their vector fallback in the meantime. Cached per id/view/color.
 * @param {string} id tank id
 * @param {string} view 'top_silhouette' | 'side_silhouette'
 * @param {string} color css color the white silhouette is tinted to
 * @returns {HTMLCanvasElement|null}
 */
export function tintedIcon(id: string, view: string, color: string): HTMLCanvasElement | null {
  const key = `${id}|${view}|${color}`;
  let e = tintCache.get(key);
  if (!e) {
    const entry: TintCacheEntry = { canvas: null };
    e = entry;
    tintCache.set(key, entry);
    const img = new Image();
    img.onload = () => {
      const c = document.createElement('canvas');
      c.width = img.naturalWidth;
      c.height = img.naturalHeight;
      const x = c.getContext('2d');
      if (!x) return;
      x.drawImage(img, 0, 0);
      x.globalCompositeOperation = 'source-in';
      x.fillStyle = color;
      x.fillRect(0, 0, c.width, c.height);
      entry.canvas = c;
    };
    img.src = iconUrl(id, view);
  }
  return e.canvas;
}

/**
 * Turn a DOM element into a tinted silhouette via CSS mask: the element's
 * background color shows through the icon's alpha. Give the element explicit
 * width/height in CSS.
 * @param {HTMLElement} el
 * @param {string} id tank id
 * @param {string} view icon view name
 * @param {string} color css background color (the tint)
 */
export function maskIcon(el: HTMLElement, id: string, view: string, color: string): void {
  const u = `url(${iconUrl(id, view)})`;
  const s = el.style;
  s.webkitMaskImage = u; s.maskImage = u;
  s.webkitMaskSize = 'contain'; s.maskSize = 'contain';
  s.webkitMaskRepeat = 'no-repeat'; s.maskRepeat = 'no-repeat';
  s.webkitMaskPosition = 'center'; s.maskPosition = 'center';
  s.background = color;
}
