// src/ui/mapThumbs.ts — GENERATED map art served from public/maps/.
// Regenerate via: node tools/screenshot.mjs --width 3840 --height 2160 --dyn-scale 1 && node tools/map-thumbs.mjs
// Empty string = no thumbnail yet; the picker falls back to a CSS gradient.

export const MAP_THUMBS = Object.freeze({
  verdant: '/maps/thumbs/verdant.webp',
  desert: '/maps/thumbs/desert.webp',
  winter: '/maps/thumbs/winter.webp',
  urban: '/maps/thumbs/urban.webp',
  coastal: '/maps/thumbs/coastal.webp',
  autumn: '/maps/thumbs/autumn.webp',
  steppe: '/maps/thumbs/steppe.webp',
  railyard: '/maps/thumbs/railyard.webp',
  frontier: '/maps/thumbs/frontier.webp',
  fjord: '/maps/thumbs/fjord.webp',
  delta: '/maps/thumbs/delta.webp',
  badlands: '/maps/thumbs/badlands.webp',
  monsoon: '/maps/thumbs/monsoon.webp',
  alpine: '/maps/thumbs/alpine.webp',
  caldera: '/maps/thumbs/caldera.webp',
  foundry: '/maps/thumbs/foundry.webp',
  ruinspires: '/maps/thumbs/ruinspires.webp',
  blackglass: '/maps/thumbs/blackglass.webp',
  titan_gorge: '/maps/thumbs/titan_gorge.webp',
  skybridge: '/maps/thumbs/skybridge.webp',
  polders: '/maps/thumbs/polders.webp',
  copper_mesa: '/maps/thumbs/copper_mesa.webp',
  airfield: '/maps/thumbs/airfield.webp',
  oasis: '/maps/thumbs/oasis.webp',
  whiteout: '/maps/thumbs/whiteout.webp',
  orchard: '/maps/thumbs/orchard.webp',
  longleaf: '/maps/thumbs/longleaf.webp',
  mangrove: '/maps/thumbs/mangrove.webp',
  saltwind: '/maps/thumbs/saltwind.webp',
  reservoir: '/maps/thumbs/reservoir.webp',
});

export const MAP_HEROES = Object.freeze({
  verdant: '/maps/verdant.webp',
  desert: '/maps/desert.webp',
  winter: '/maps/winter.webp',
  urban: '/maps/urban.webp',
  coastal: '/maps/coastal.webp',
  autumn: '/maps/autumn.webp',
  steppe: '/maps/steppe.webp',
  railyard: '/maps/railyard.webp',
  frontier: '/maps/frontier.webp',
  fjord: '/maps/fjord.webp',
  delta: '/maps/delta.webp',
  badlands: '/maps/badlands.webp',
  monsoon: '/maps/monsoon.webp',
  alpine: '/maps/alpine.webp',
  caldera: '/maps/caldera.webp',
  foundry: '/maps/foundry.webp',
  ruinspires: '/maps/ruinspires.webp',
  blackglass: '/maps/blackglass.webp',
  titan_gorge: '/maps/titan_gorge.webp',
  skybridge: '/maps/skybridge.webp',
  polders: '/maps/polders.webp',
  copper_mesa: '/maps/copper_mesa.webp',
  airfield: '/maps/airfield.webp',
  oasis: '/maps/oasis.webp',
  whiteout: '/maps/whiteout.webp',
  orchard: '/maps/orchard.webp',
  longleaf: '/maps/longleaf.webp',
  mangrove: '/maps/mangrove.webp',
  saltwind: '/maps/saltwind.webp',
  reservoir: '/maps/reservoir.webp',
});

export type MapThumbnailId = keyof typeof MAP_THUMBS;
