// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "spz_puma": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          1.8682017,
          1.30006,
          -0.35
        ],
        "quaternion": [
          -0.0035355,
          0.7070979,
          0.0035355,
          0.7070979
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0019928
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          -1.8682017,
          1.30006,
          -0.35
        ],
        "quaternion": [
          -0.0035355,
          -0.7070979,
          -0.0035355,
          0.7070979
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0019928
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.866,
          1.5402,
          -0.75
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "spz_puma",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0009
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          0.7931399,
          0.3610727,
          -0.5497893
        ],
        "quaternion": [
          -0.0623772,
          0.6917737,
          0.0646075,
          0.7165083
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -0.9072423,
          0.3610722,
          -0.5497212
        ],
        "quaternion": [
          -0.0620094,
          -0.6876953,
          -0.0649606,
          0.7204236
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "spz_puma_s1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8436781,
          0.3981693,
          -0.8460659
        ],
        "quaternion": [
          -0.1307634,
          -0.6988455,
          -0.1293369,
          0.691222
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "spz_puma_s1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0080839
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8184368,
          0.1951558,
          0.7686822
        ],
        "quaternion": [
          -0.0389413,
          -0.5844904,
          -0.0538774,
          0.8086728
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "spz_puma_s1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.1661022
      }
    ]
  },
  "type89_light_tiger": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0390448,
          0.3706052,
          -1.01808
        ],
        "quaternion": [
          -0.0954588,
          -0.7006337,
          -0.0954588,
          0.7006337
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type89_light_tiger",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.012287
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0596091,
          0.1461925,
          -0.18216
        ],
        "quaternion": [
          -0.0231401,
          -0.706728,
          -0.0231401,
          0.706728
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type89_light_tiger",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.297658
      }
    ]
  },
  "bmp3_rok": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          1.0593018,
          0.4152197,
          -0.1264
        ],
        "quaternion": [
          -0.0247438,
          0.7066737,
          0.0247438,
          0.7066737
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "bmp3_rok",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0078679
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          0.8367325,
          0.4172446,
          -0.4996969
        ],
        "quaternion": [
          -0.1832179,
          0.8007314,
          0.1272083,
          0.5559483
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "bmp3_rok",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0165694
      }
    ]
  },
  "ua_m2a3_bradley": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.7756163,
          1.462247,
          -0.3904
        ],
        "quaternion": [
          -0.0042426,
          -0.7070941,
          -0.0042426,
          0.7070941
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_m2a3_bradley",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.7756163,
          1.462247,
          0.3345
        ],
        "quaternion": [
          -0.0042426,
          -0.7070941,
          -0.0042426,
          0.7070941
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_m2a3_bradley",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "bmpt_terminator2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          0.7451413,
          0.3174996,
          -0.3242746
        ],
        "quaternion": [
          -0.1568237,
          0.6569818,
          0.1712132,
          0.7172637
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "bmpt_terminator2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          0.701264,
          0.5034996,
          -0.8346746
        ],
        "quaternion": [
          -0.1568237,
          0.6569818,
          0.1712132,
          0.7172637
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "bmpt_terminator2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "bwp1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.7342586,
          1.237148,
          -0.5845749
        ],
        "quaternion": [
          -0.0063639,
          0.7070781,
          0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "bwp1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.7342586,
          1.237148,
          -1.3209363
        ],
        "quaternion": [
          -0.0063639,
          0.7070781,
          0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "bwp1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "marder1a3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          -1.7236905,
          1.348708,
          -0.2586
        ],
        "quaternion": [
          -0.0063639,
          -0.7070781,
          -0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "marder1a3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0025481
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          -1.7236905,
          1.348708,
          0.4663
        ],
        "quaternion": [
          -0.0063639,
          -0.7070781,
          -0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "marder1a3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006217
      }
    ]
  },
  "m3a3_bradley": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -0.9267605,
          0.1806105,
          -1.0755573
        ],
        "quaternion": [
          -0.1065454,
          -0.6721307,
          -0.1147187,
          0.7236906
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m3a3_bradley",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -0.8852722,
          0.1174653,
          -0.1446444
        ],
        "quaternion": [
          -0.1249166,
          -0.6743621,
          -0.1325525,
          0.7155846
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m3a3_bradley",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0972488
      }
    ]
  },
  "bmp3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.621,
          1.1,
          0.9
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          1.0469036,
          0.1970188,
          0.0375279
        ],
        "quaternion": [
          -0.1145792,
          0.6977619,
          0.1145792,
          0.6977619
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "bmp3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0149522
      }
    ]
  },
  "upior": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -1.507521,
          0.950048,
          0.65
        ],
        "quaternion": [
          -0.0028284,
          -0.7071011,
          -0.0028284,
          0.7071011
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          1.507521,
          0.950048,
          0.3
        ],
        "quaternion": [
          -0.0028284,
          0.7071011,
          0.0028284,
          0.7071011
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0046003
      }
    ]
  },
  "bmpt_t90": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -0.8958049,
          0.6608,
          -2.2696154
        ],
        "quaternion": [
          0,
          -0.7109461,
          0,
          0.7032465
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "bmpt_t90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.5288968
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -1.606,
          1.2728,
          -0.4106001
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "bmpt_t90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2489568
      }
    ]
  }
});
