// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "amx30_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0120945,
          0.2955938,
          -0.9641321
        ],
        "quaternion": [
          -0.2203327,
          -0.7187709,
          -0.19326,
          0.6304542
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "amx30_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0013639
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0869743,
          0.3442121,
          -0.4238814
        ],
        "quaternion": [
          -0.1855425,
          -0.7504646,
          -0.1522461,
          0.6157906
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "amx30_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0108949
      }
    ]
  }
});
