// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "amx40_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2619609,
          0.4414922,
          -0.5168922
        ],
        "quaternion": [
          -0.1475166,
          0.7249476,
          0.1341605,
          0.6593108
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "amx40_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0045958
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.1023308,
          0.5989811,
          -1.2634365
        ],
        "quaternion": [
          -0.1536538,
          0.7336485,
          0.135689,
          0.6478726
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "amx40_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
