// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "challenger1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.656,
          0.403105,
          -0.5615
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.00072
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.656,
          0.403105,
          -0.017
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.00072
      }
    ]
  },
  "fv4034": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          0.8,
          1.3697338,
          3.5880871
        ],
        "quaternion": [
          -0.6952285,
          0,
          0,
          0.7187888
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.3,
        "pos": [
          -1.376,
          0.2744954,
          -1.45
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.376,
          0.267,
          -1.81324
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "fv4034",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      }
    ]
  },
  "challenger2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          0.8,
          1.3697338,
          3.5880871
        ],
        "quaternion": [
          -0.6952285,
          0,
          0,
          0.7187888
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.3,
        "pos": [
          -1.376,
          0.2744954,
          -1.45
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.346,
          0.38,
          -1.0718
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      }
    ]
  },
  "challenger2e": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.3,
        "pos": [
          -1.376,
          0.2744954,
          -1.45
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.47,
          0.2604,
          -0.88318
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger2e",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0028
      }
    ]
  },
  "ua_challenger2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.861,
          1.1445,
          -0.8149999
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_challenger2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.3,
        "pos": [
          -1.376,
          0.2744954,
          -1.45
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      }
    ]
  },
  "challenger_3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.32,
        "pos": [
          0.8,
          1.1587067,
          3.2891343
        ],
        "quaternion": [
          -0.5569076,
          0,
          0,
          0.8305744
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.34,
        "pos": [
          1.3318842,
          0.3948629,
          -1.4001554
        ],
        "quaternion": [
          -0.0307853,
          0.7155428,
          0.0299981,
          0.6972452
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.4756731
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.34,
        "pos": [
          -1.3329488,
          0.3949269,
          -1.4000642
        ],
        "quaternion": [
          -0.0305564,
          -0.7102228,
          -0.0302312,
          0.7026635
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.4729372
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.3309735,
          0.3645153,
          -1.8280641
        ],
        "quaternion": [
          -0.0305564,
          -0.7102228,
          -0.0302312,
          0.7026635
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger_3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0031883
      }
    ]
  },
  "challenger_3x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.6511432,
          0.6938332,
          -1.9791999
        ],
        "quaternion": [
          -0.1851978,
          -0.6824235,
          -0.1851978,
          0.6824235
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger_3x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.122143
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.3620078,
          0.4162626,
          0.1880001
        ],
        "quaternion": [
          -0.0391032,
          -0.7060247,
          -0.0391032,
          0.7060247
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "challenger_3x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.002791
      }
    ]
  }
});
