// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "chieftain_mk10_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.1869506,
          0.1648771,
          -0.6742703
        ],
        "quaternion": [
          0.0053808,
          0.883133,
          -0.002858,
          0.4690831
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain_mk10_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0000239
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.1820524,
          0.3606622,
          0.3500575
        ],
        "quaternion": [
          -0.1768738,
          0.5499794,
          0.2498964,
          0.7770393
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain_mk10_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0047923
      }
    ]
  }
});
