// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "chieftain5_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1168616,
          0.2451336,
          -0.8684983
        ],
        "quaternion": [
          -0.0265298,
          -0.7828104,
          -0.0210574,
          0.6213378
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain5_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0021237
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.037423,
          0.4889092,
          -1.0794971
        ],
        "quaternion": [
          -0.0651175,
          -0.7733276,
          -0.0529165,
          0.6284297
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain5_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0088581
      }
    ]
  }
});
