// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "amx40": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2491068,
          0.7066282,
          -0.2941343
        ],
        "quaternion": [
          -0.2072035,
          0.6594835,
          0.2165945,
          0.689373
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "amx40",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0011228
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.2243157,
          0.7073446,
          -0.9735147
        ],
        "quaternion": [
          -0.2807232,
          0.6933556,
          0.2490631,
          0.6151586
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "amx40",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0129051
      }
    ]
  }
});
