// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "carro45t": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.300139,
          0.5050874,
          0.1353029
        ],
        "quaternion": [
          -0.1736522,
          0.6852762,
          0.1737361,
          0.6856072
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "carro45t",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.3418077,
          0.4518148,
          -0.509375
        ],
        "quaternion": [
          -0.1840596,
          0.6750603,
          0.1879346,
          0.6892722
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "carro45t",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0000495
      }
    ]
  },
  "ariete": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.3122426,
          0.3035107,
          -0.7501913
        ],
        "quaternion": [
          -0.011709,
          0.7181948,
          0.0113414,
          0.6956511
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000078
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.3125179,
          0.3035183,
          -0.7501913
        ],
        "quaternion": [
          -0.0113405,
          -0.7182011,
          -0.0109845,
          0.6956565
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000077
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.2754479,
          0.4341846,
          0.2325619
        ],
        "quaternion": [
          -0.0104014,
          -0.6730988,
          -0.0114258,
          0.7393911
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0001301
      }
    ]
  },
  "ariete_c1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.407565,
          0.3799413,
          -0.5332799
        ],
        "quaternion": [
          -0.0065578,
          0.7070764,
          0.0065578,
          0.7070764
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.3645,
          0.462858,
          -1.3499199
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ariete_c2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4078217,
          0.3661033,
          -0.6863999
        ],
        "quaternion": [
          -0.0065578,
          -0.7070764,
          -0.0065578,
          0.7070764
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.5020001,
          0.44902,
          -1.2478399
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ariete_c2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
