// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "jpz_e100_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.28,
        "pos": [
          1.3799663,
          2.313312,
          -0.9750955
        ],
        "quaternion": [
          -0.1242087,
          0.6961122,
          0.1242087,
          0.6961122
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "jpz_e100_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.28,
        "pos": [
          1.3805567,
          2.3133102,
          -0.4673966
        ],
        "quaternion": [
          -0.1250531,
          0.7014073,
          0.1231639,
          0.6908112
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "jpz_e100_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0008091
      }
    ]
  }
});
