// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "stb1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.1686715,
          0.3562229,
          -0.4005923
        ],
        "quaternion": [
          -0.3919919,
          -0.5985022,
          -0.3827996,
          0.5844672
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "stb1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0042555
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.276797,
          0.1916277,
          -0.0515862
        ],
        "quaternion": [
          -0.0953022,
          -0.6740595,
          -0.1025455,
          0.7252901
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "stb1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006414
      }
    ]
  },
  "type90a": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          1.356968,
          0.2856,
          -0.6402564
        ],
        "quaternion": [
          0,
          0.7447793,
          0,
          0.6673108
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.1859999,
          0.338232,
          -1.409088
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type90a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "type10b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.286,
        "pos": [
          0,
          1.0345518,
          3.7680001
        ],
        "quaternion": [
          0,
          0,
          0,
          1
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.242,
        "pos": [
          0.935,
          1.43,
          -3.7680499
        ],
        "quaternion": [
          0,
          1,
          0,
          0
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          -1.568,
          1.55562,
          -0.8276704
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "type10b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.264,
        "pos": [
          1.601,
          0.4079908,
          -0.55
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0219783
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.579,
          0.473,
          -0.902
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
