// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "k1a1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5271339,
          0.327116,
          -0.4366394
        ],
        "quaternion": [
          -0.1197346,
          -0.7087162,
          -0.1158197,
          0.6855441
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "k1a1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.5668276,
          0.2451911,
          -0.0461481
        ],
        "quaternion": [
          -0.1316442,
          -0.694032,
          -0.1319049,
          0.6954067
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "k1a1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.002671
      }
    ]
  }
});
