// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "kf51_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.407179,
          0.506059,
          -1.4139197
        ],
        "quaternion": [
          -0.0810766,
          -0.7065617,
          -0.080141,
          0.6984086
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4181926,
          0.5058821,
          -1.0398256
        ],
        "quaternion": [
          -0.071915,
          -0.7218888,
          -0.0682274,
          0.6848721
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0015653
      }
    ]
  }
});
