// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "k2b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.9042223,
          1.179928,
          -0.42
        ],
        "quaternion": [
          0.0042426,
          -0.7070941,
          0.0042426,
          0.7070941
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          -1.9042823,
          1.192928,
          -0.0369749
        ],
        "quaternion": [
          0.0042426,
          -0.7070941,
          0.0042426,
          0.7070941
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "k2b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0174567
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.3,
        "pos": [
          1.3882909,
          0.2962777,
          -0.8497185
        ],
        "quaternion": [
          -0.1407684,
          0.6758135,
          0.1475359,
          0.7083033
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0054995
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.3,
        "pos": [
          -1.4058462,
          0.2971585,
          -0.85
        ],
        "quaternion": [
          -0.1441919,
          -0.692249,
          -0.1441919,
          0.692249
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.006738
      }
    ]
  }
});
