// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "leclerc_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.5773832,
          0.3394013,
          -1.4591764
        ],
        "quaternion": [
          0.0000343,
          0.7128717,
          -0.0000337,
          0.7012944
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leclerc_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0001073
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.5834705,
          0.2726959,
          -1.0168858
        ],
        "quaternion": [
          0,
          0.7088314,
          0,
          0.705378
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leclerc_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0002841
      }
    ]
  }
});
