// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "leclerc_classic_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.7111912,
          0.2565367,
          -1.0991924
        ],
        "quaternion": [
          0,
          -0.7086895,
          0,
          0.7055205
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leclerc_classic_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0017215
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.7105434,
          0.2565367,
          -0.6239474
        ],
        "quaternion": [
          0,
          -0.7064447,
          0,
          0.7077683
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leclerc_classic_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000054
      }
    ]
  }
});
