// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "leo1a5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          1.2580163,
          0.4883283,
          -0.5203867
        ],
        "quaternion": [
          -0.2055219,
          0.6999873,
          0.1926779,
          0.6562421
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0141106
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          -1.2580162,
          0.4883283,
          -0.5203867
        ],
        "quaternion": [
          -0.2055219,
          -0.6999874,
          -0.1926779,
          0.656242
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0141105
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1718013,
          0.3741,
          0.3375282
        ],
        "quaternion": [
          0,
          -0.5529319,
          0,
          0.8332264
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo1a5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0098551
      }
    ]
  },
  "leopard2_proto": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          0.62,
          1.22,
          -3.786
        ],
        "quaternion": [
          0,
          1,
          0,
          0
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.2285268,
          0.2599383,
          -0.3252579
        ],
        "quaternion": [
          0,
          0.722145,
          0,
          0.6917417
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.2285268,
          0.2599383,
          -0.3252579
        ],
        "quaternion": [
          0,
          -0.722145,
          0,
          0.6917417
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a4": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.7836375,
          1.1912438,
          -0.7159999
        ],
        "quaternion": [
          -0.0055238,
          -0.7070852,
          -0.0055238,
          0.7070852
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0359597
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.7836375,
          1.1912438,
          0.5416
        ],
        "quaternion": [
          -0.0055238,
          -0.7070852,
          -0.0055238,
          0.7070852
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000688
      }
    ]
  },
  "leo2a4m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.9335034,
          1.041308,
          -0.8
        ],
        "quaternion": [
          -0.0063639,
          -0.7070781,
          -0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.9335034,
          1.041308,
          0.0084999
        ],
        "quaternion": [
          -0.0063639,
          -0.7070781,
          -0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.521,
          0.1695,
          -0.9077
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0014497
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.521,
          0.1695,
          -1.2728
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.009941
      }
    ]
  },
  "leo2a5_a5nl": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.521,
          0.15885,
          -1.1511
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a5_a5nl",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.521,
          0.15885,
          -0.72515
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a5_a5nl",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a6": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.2706878,
          0.4143574,
          0.02004
        ],
        "quaternion": [
          -0.2756149,
          -0.6511808,
          -0.2756149,
          0.6511808
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.1112875,
          0.5689274,
          0.27869
        ],
        "quaternion": [
          -0.2756149,
          -0.6511808,
          -0.2756149,
          0.6511808
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a6m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1313005,
          0.541911,
          -1.1864
        ],
        "quaternion": [
          -0.2487083,
          -0.6619246,
          -0.2487083,
          0.6619246
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2050105,
          0.457671,
          -0.5561
        ],
        "quaternion": [
          -0.2487083,
          -0.6619246,
          -0.2487083,
          0.6619246
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2_revolution_proto": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          1.6088411,
          0.4218878,
          0.525
        ],
        "quaternion": [
          -0.1126766,
          0.6980716,
          0.1126766,
          0.6980716
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.4767245,
          0.2889502,
          -1.5963293
        ],
        "quaternion": [
          -0.0308933,
          0.7369948,
          0.0282779,
          0.6745996
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2_revolution_proto",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0014819
      }
    ]
  },
  "leo2_revolution": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.5899027,
          0.35844,
          -1.6185497
        ],
        "quaternion": [
          0,
          0.7365307,
          0,
          0.6764041
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2_revolution",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.5227652,
          0.35844,
          -2.4032029
        ],
        "quaternion": [
          0,
          0.7372812,
          0,
          0.675586
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2_revolution",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a7v": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.36,
        "pos": [
          1.386,
          0.18,
          -0.65
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.36,
        "pos": [
          -1.386,
          0.18,
          -0.65
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.1392549,
          0.5418074,
          -0.4187999
        ],
        "quaternion": [
          -0.2756149,
          -0.6511808,
          -0.2756149,
          0.6511808
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a7v",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "kf51": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3466138,
          0.5582833,
          -1.3952
        ],
        "quaternion": [
          -0.0863967,
          -0.7018088,
          -0.0863967,
          0.7018088
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3710437,
          0.5587559,
          -0.72915
        ],
        "quaternion": [
          -0.1151318,
          -0.6976709,
          -0.1151318,
          0.6976709
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "kf51b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4549127,
          0.4168,
          -1.0457587
        ],
        "quaternion": [
          0,
          -0.7449088,
          0,
          0.6671663
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0148984
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4815036,
          0.4168,
          -0.5056587
        ],
        "quaternion": [
          0,
          -0.7449088,
          0,
          0.6671663
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0003
      }
    ]
  },
  "leo2a6_ua": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.426,
          1.1136,
          -0.6707
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6_ua",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.3119488
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2112,
        "pos": [
          0.9021321,
          0.7925773,
          -1.301
        ],
        "quaternion": [
          -0.1132659,
          0.6979762,
          0.1132659,
          0.6979762
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6_ua",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.1086684
      }
    ]
  }
});
