// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "merkava1b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.1323907,
          0.3435445,
          -0.1613269
        ],
        "quaternion": [
          -0.1193129,
          -0.7240394,
          -0.1104607,
          0.6703207
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava1b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.0236001,
          0.442125,
          -1.0501627
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava1b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": null
      }
    ]
  },
  "merkava2b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.1700996,
          0.352775,
          -0.9166489
        ],
        "quaternion": [
          -0.2376002,
          0.6886878,
          0.223413,
          0.6475662
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava2b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0075997
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.158,
          0.3984447,
          -1.79236
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava2b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0650001
      }
    ]
  },
  "merkava2d": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.5070285,
          0.4067037,
          0.1957876
        ],
        "quaternion": [
          -0.0621567,
          -0.7179865,
          -0.0597939,
          0.6906928
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava2d",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0029148
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.4932342,
          0.2888803,
          -0.6770924
        ],
        "quaternion": [
          -0.0621567,
          -0.7179865,
          -0.0597939,
          0.6906928
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava2d",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0030026
      }
    ]
  },
  "merkava3c": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          1.8391329,
          1.1283463,
          -0.2934999
        ],
        "quaternion": [
          -0.0063639,
          0.7070781,
          0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "merkava3c",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.001684
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          1.8358741,
          1.1281303,
          -1.1129999
        ],
        "quaternion": [
          0.0063639,
          0.7070781,
          -0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "merkava3c",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.001684
      }
    ]
  },
  "merkava3d": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.8374336,
          1.1702374,
          -1.1832383
        ],
        "quaternion": [
          -0.0063638,
          -0.7070781,
          -0.0063638,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "merkava3d",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.8375733,
          1.1700214,
          -0.73167
        ],
        "quaternion": [
          0.0063638,
          -0.7070781,
          0.0063638,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "merkava3d",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "merkava4b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.1807999,
          0.39072,
          -2.2579873
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava4b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.7025481,
          0.3380616,
          -1.8754328
        ],
        "quaternion": [
          -0.0366797,
          0.7061546,
          0.0366797,
          0.706155
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "merkava4b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.1868234
      }
    ]
  }
});
