// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "m60a1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          1.1646638,
          0.5408169,
          -1.5007821
        ],
        "quaternion": [
          -0.051741,
          0.7499993,
          0.0453836,
          0.6578482
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0008448
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          -1.1950495,
          0.5408239,
          -1.5002969
        ],
        "quaternion": [
          -0.0499169,
          -0.7226658,
          -0.0475054,
          0.687754
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0012421
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          0.846,
          0.75731,
          -0.4892
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m60a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      }
    ]
  },
  "m48": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.0906982,
          0.6143415,
          -0.6448954
        ],
        "quaternion": [
          -0.2077428,
          -0.6730815,
          -0.2093295,
          0.6782222
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m48",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0003191
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.0602593,
          0.6141647,
          -0.1069449
        ],
        "quaternion": [
          -0.2030405,
          -0.6999184,
          -0.1907765,
          0.6576421
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m48",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0067951
      }
    ]
  },
  "m60a2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.391,
          0.45,
          -0.03
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.306,
          0.45,
          -1.48
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.3041029,
          0.6362,
          -0.4359444
        ],
        "quaternion": [
          0,
          0.8338824,
          0,
          0.5519421
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m60a2",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0006
      }
    ]
  },
  "m46_patton": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -0.8197,
          0.429,
          -1.186
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.0349133,
          0.4250721,
          -0.1940927
        ],
        "quaternion": [
          -0.1764949,
          -0.6999349,
          -0.1692114,
          0.6710501
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m46_patton",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0010168
      }
    ]
  },
  "m47_patton": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.8687618,
          0.3653041,
          -1.2627515
        ],
        "quaternion": [
          -0.0207443,
          0.749797,
          0.0182901,
          0.6610897
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0045467
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -0.7757403,
          0.3654921,
          -1.2616957
        ],
        "quaternion": [
          -0.0297517,
          -0.6883004,
          -0.0313009,
          0.7241393
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0046707
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          0.9016888,
          0.4430646,
          0.3444852
        ],
        "quaternion": [
          -0.2327552,
          0.5989404,
          0.2775421,
          0.7141889
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m47_patton",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0066802
      }
    ]
  },
  "m26_pershing": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.0514271,
          0.4071951,
          -0.3759203
        ],
        "quaternion": [
          -0.3046307,
          -0.6059905,
          -0.3300429,
          0.6565419
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m26_pershing",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0138945
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.2383703,
          0.3631951,
          -0.0366926
        ],
        "quaternion": [
          -0.3404319,
          -0.6325778,
          -0.3296749,
          0.6125895
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m26_pershing",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0005558
      }
    ]
  },
  "m45_patton": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -0.4824536,
          0.3454739,
          -1.7278967
        ],
        "quaternion": [
          0.1643273,
          0.8931512,
          0.0757563,
          -0.4117505
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0860117
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.0389245,
          0.123149,
          -0.4796303
        ],
        "quaternion": [
          0,
          0.8722715,
          0,
          0.4890219
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m45_patton",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0017535
      }
    ]
  },
  "m60a3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          1.1646638,
          0.5408169,
          -1.5007821
        ],
        "quaternion": [
          -0.051741,
          0.7499993,
          0.0453836,
          0.6578482
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0008448
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          -1.1950495,
          0.5408239,
          -1.5002969
        ],
        "quaternion": [
          -0.0499169,
          -0.7226658,
          -0.0475054,
          0.687754
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0012421
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.1836557,
          0.9938868,
          -0.4475091
        ],
        "quaternion": [
          -0.020298,
          -0.7219242,
          -0.0194398,
          0.6914011
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m60a3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0124147
      }
    ]
  }
});
