// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t62mv1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          1.4561296,
          0.2903465,
          -0.2987863
        ],
        "quaternion": [
          -0.0186289,
          0.6312795,
          0.0228698,
          0.7749942
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0038482
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -1.4561296,
          0.2903465,
          -0.2987863
        ],
        "quaternion": [
          -0.0186289,
          -0.6312796,
          -0.0228698,
          0.7749942
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0038482
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4121064,
          0.5192377,
          -0.5605697
        ],
        "quaternion": [
          -0.2117147,
          -0.674668,
          -0.2117147,
          0.674668
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t62mv1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t64bv1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.7003496,
          0.5888552,
          -0.4494648
        ],
        "quaternion": [
          -0.495811,
          0.5285131,
          0.4714641,
          0.5025604
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t64bv1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0064511
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.086,
          0.448,
          -0.9538019
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t64bv1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
