// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "m551_sheridan": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          -1.1930161,
          0.4253775,
          -0.3615784
        ],
        "quaternion": [
          0.3545374,
          -0.7112209,
          0.2708098,
          0.5432588
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0086098
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.0915552,
          0.4732455,
          0.4636703
        ],
        "quaternion": [
          -0.2935412,
          0.5976757,
          0.3288956,
          0.6696604
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m551_sheridan",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0087833
      }
    ]
  },
  "m551a1_tts": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.7867048,
          0.5223095,
          -0.6765391
        ],
        "quaternion": [
          -0.3567414,
          0.7042456,
          0.2773773,
          0.5475724
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m551a1_tts",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0011353
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          1.1755131,
          0.3977606,
          0.058932
        ],
        "quaternion": [
          -0.1842847,
          0.7185323,
          0.1666077,
          0.6496094
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "m551a1_tts",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0124567
      }
    ]
  }
});
