// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "strv122_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.8277116,
          1.522774,
          -2.1374835
        ],
        "quaternion": [
          0.0186489,
          0.7076559,
          -0.018607,
          0.7060659
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "strv122_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0013771
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.8274989,
          1.522665,
          -0.141363
        ],
        "quaternion": [
          0.0250693,
          0.7068387,
          -0.0250568,
          0.7064862
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "strv122_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0000354
      }
    ]
  }
});
