// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "strv81": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.471,
          0.3169,
          -0.393
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "strv81",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0025954
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.5401204,
          0.1014072,
          -0.0245
        ],
        "quaternion": [
          -0.0744942,
          -0.7031718,
          -0.0744942,
          0.7031718
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "strv81",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0040096
      }
    ]
  },
  "udes03": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          1.339804,
          1.4978605,
          -0.7199759
        ],
        "quaternion": [
          0.1279401,
          0.6939925,
          -0.1284544,
          0.6967821
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0888677
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.3398032,
          1.4978608,
          -0.720104
        ],
        "quaternion": [
          0.1293037,
          -0.7013889,
          0.1270817,
          0.6893362
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0898129
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          1.1647973,
          1.0205348,
          0.8702093
        ],
        "quaternion": [
          0.1337101,
          0.6816688,
          -0.1384607,
          0.705888
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "udes03",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "strv103a": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          -0.946,
          1.2504251,
          2.8628999
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "strv103a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          -1.5384746,
          1.4612791,
          3.0432381
        ],
        "quaternion": [
          0.4436485,
          -0.5082518,
          0.4854064,
          0.5560905
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "strv103a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0144963
      }
    ]
  },
  "strv103": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          0.7602415,
          1.26015,
          2.7164924
        ],
        "quaternion": [
          0,
          0.5483037,
          0,
          0.8362793
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "strv103",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          1.2571393,
          1.483121,
          -3.2455685
        ],
        "quaternion": [
          0.3313208,
          0.5665081,
          -0.3809145,
          0.6513057
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "strv103",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0024838
      }
    ]
  },
  "cv90": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.9112876,
          0.3329209,
          -0.2651131
        ],
        "quaternion": [
          -0.184128,
          -0.6919927,
          -0.1794885,
          0.6745568
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cv90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0009586
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.8161896,
          0.5154409,
          0.0556469
        ],
        "quaternion": [
          -0.184128,
          -0.6919927,
          -0.1794885,
          0.6745568
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "cv90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "strv122": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.5703876,
          0.4304795,
          -0.82
        ],
        "quaternion": [
          -0.0282767,
          -0.7065412,
          -0.0282767,
          0.7065412
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.5779718,
          0.3608795,
          -1.1511
        ],
        "quaternion": [
          -0.0282767,
          0.7065412,
          0.0282767,
          0.7065412
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "strv122",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "cv90_mkiv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          -1.014,
          0.60768,
          -1.05804
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "cv90_mkiv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.7022145
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          1.014,
          0.60768,
          -1.05804
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "cv90_mkiv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.7022145
      }
    ]
  }
});
