// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t62mv1_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.209806,
          0.1714502,
          -0.0934387
        ],
        "quaternion": [
          0,
          -0.7787987,
          0,
          0.6272739
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t62mv1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0086636
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1066772,
          0.1714502,
          -0.4975036
        ],
        "quaternion": [
          0,
          0.8671422,
          0,
          -0.4980607
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t62mv1_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0152015
      }
    ]
  }
});
