// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t72b_1987_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.1859055,
          0.206088,
          -0.3044743
        ],
        "quaternion": [
          -0.0740944,
          0.8611141,
          0.0431198,
          0.5011319
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72b_1987_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0174351
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.5689613,
          0.2057452,
          -1.1199012
        ],
        "quaternion": [
          -0.061397,
          0.9258224,
          0.0246776,
          0.3721212
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72b_1987_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0067688
      }
    ]
  }
});
