// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t72b3_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2488422,
          0.2566327,
          -0.1264258
        ],
        "quaternion": [
          -0.0284451,
          -0.743481,
          -0.0255444,
          0.6676633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72b3_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0165046
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.5822977,
          0.2568104,
          -1.1653121
        ],
        "quaternion": [
          0.0863474,
          0.947794,
          0.0278507,
          -0.3057041
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72b3_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0041831
      }
    ]
  }
});
