// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t72bu_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.222456,
          0.2620505,
          -0.2780553
        ],
        "quaternion": [
          0,
          0.838391,
          0,
          0.5450692
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72bu_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0041815
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.5992424,
          0.3710386,
          -1.1767048
        ],
        "quaternion": [
          0,
          0.9372067,
          0,
          0.3487745
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t72bu_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0110177
      }
    ]
  }
});
