// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t80": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.3241192,
          0.2195253,
          -0.3027002
        ],
        "quaternion": [
          0.0377539,
          0.8506422,
          -0.0232509,
          0.523872
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3241191,
          0.2195253,
          -0.3027002
        ],
        "quaternion": [
          0.037754,
          -0.8506422,
          0.023251,
          0.523872
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.4331493,
          0.2932171,
          -0.0140042
        ],
        "quaternion": [
          0.0325406,
          0.7848281,
          -0.0256371,
          0.6183273
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t80",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t80b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.3241192,
          0.2195253,
          -0.3027002
        ],
        "quaternion": [
          0.0377539,
          0.8506422,
          -0.0232509,
          0.523872
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3241191,
          0.2195253,
          -0.3027002
        ],
        "quaternion": [
          0.037754,
          -0.8506422,
          0.023251,
          0.523872
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4577548,
          0.3015141,
          0.0981
        ],
        "quaternion": [
          0.0286561,
          -0.7065259,
          0.0286561,
          0.7065259
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t80b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0136026
      }
    ]
  },
  "t80bv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.3241192,
          0.2195253,
          -0.3027002
        ],
        "quaternion": [
          0.0377532,
          0.8506423,
          -0.0232505,
          0.523872
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2624169
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3241192,
          0.2195253,
          -0.3027002
        ],
        "quaternion": [
          0.0377542,
          -0.8506422,
          0.0232511,
          0.523872
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.262417
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.3561155,
          0.4253213,
          -0.1100143
        ],
        "quaternion": [
          -0.3505983,
          0.6670332,
          0.3058497,
          0.5818965
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t80bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0119028
      }
    ]
  },
  "t84": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.751,
          0.766843,
          -2.3076001
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "t84",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.751,
          0.766843,
          -3.0875001
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "t84",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
