// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t80u_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2497629,
          0.1796387,
          -0.4978995
        ],
        "quaternion": [
          0,
          -0.8588215,
          0,
          0.5122749
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t80u_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0097086
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0614791,
          0.1796387,
          -0.8092765
        ],
        "quaternion": [
          0,
          0.8854167,
          0,
          -0.4647981
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t80u_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0090291
      }
    ]
  }
});
