// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "pt91m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.3002843,
          0.24338,
          -0.3011577
        ],
        "quaternion": [
          -0.232486,
          0.7364967,
          0.1912202,
          0.6057703
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0625822
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3002843,
          0.24338,
          -0.3011577
        ],
        "quaternion": [
          -0.2324859,
          -0.7364967,
          -0.1912203,
          0.6057703
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2082499
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -0.5984839,
          0.3382166,
          -0.9826225
        ],
        "quaternion": [
          0.5215579,
          0.6026532,
          0.395241,
          -0.4566957
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "pt91m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t90": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.0333622,
          0.3992434,
          -1.3922033
        ],
        "quaternion": [
          -0.0676667,
          -0.7611755,
          -0.0571143,
          0.6424726
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.4004122,
          0.3985853,
          0.3175893
        ],
        "quaternion": [
          -0.0211688,
          -0.6511015,
          -0.0246539,
          0.7582947
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0094448
      }
    ]
  },
  "t90a": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.6185539,
          0.10675,
          -1.5836288
        ],
        "quaternion": [
          0,
          0.7176335,
          0,
          0.6964209
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0077881
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.2155189,
          0.4222885,
          0.0083077
        ],
        "quaternion": [
          -0.2304606,
          0.7025491,
          0.2098583,
          0.6397438
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t90a_vladimir": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.3826577,
          0.2355,
          -0.691368
        ],
        "quaternion": [
          0,
          -0.6782645,
          0,
          0.7348178
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_vladimir",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0057576
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          -1.1937633,
          0.4791295,
          -0.8909543
        ],
        "quaternion": [
          -0.1116375,
          -0.714071,
          -0.1067518,
          0.6828204
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_vladimir",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0035675
      }
    ]
  },
  "t90a_burlak": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          0.9859912,
          0.4226153,
          -1.5825224
        ],
        "quaternion": [
          -0.0709102,
          0.7976612,
          0.0530336,
          0.59657
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_burlak",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0019486
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.0533363,
          0.252985,
          -1.2382426
        ],
        "quaternion": [
          0.1494883,
          0.7627854,
          -0.1209944,
          0.6173913
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90a_burlak",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0063165
      }
    ]
  },
  "t90sm": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.4863963,
          0.3038142,
          -0.05
        ],
        "quaternion": [
          -0.2387832,
          0.6655694,
          0.2387832,
          0.6655694
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.022917
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.4863963,
          0.3038142,
          -0.05
        ],
        "quaternion": [
          -0.2387832,
          -0.6655694,
          -0.2387832,
          0.6655694
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.022917
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.141,
          0.3824,
          -1.33472
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90sm",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "t90m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4480341,
          0.165569,
          -0.7226291
        ],
        "quaternion": [
          0.1393199,
          -0.7743919,
          0.1092811,
          0.6074247
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2579747
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2128691,
          0.4837245,
          -0.9243102
        ],
        "quaternion": [
          -0.3260054,
          -0.6973086,
          -0.2703507,
          0.5782661
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0133568
      }
    ]
  },
  "t90ms": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.9610577,
          0.6983223,
          -0.8166105
        ],
        "quaternion": [
          -0.3780458,
          0.6207669,
          0.3572425,
          0.586607
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90ms",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0162578
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.0750685,
          0.5469447,
          -1.2616064
        ],
        "quaternion": [
          -0.1696276,
          0.7701519,
          0.1322612,
          0.6004993
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90ms",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0045695
      }
    ]
  },
  "t90m_proryv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4480341,
          0.165569,
          -0.7226291
        ],
        "quaternion": [
          0.1393199,
          -0.7743919,
          0.1092811,
          0.6074247
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m_proryv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2579747
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.6783698,
          0.0550144,
          0.3690795
        ],
        "quaternion": [
          -0.1390394,
          -0.7239085,
          -0.1274581,
          0.6636105
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90m_proryv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      }
    ]
  }
});
