// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "t90_x": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.3051125,
          0.225134,
          -0.1571486
        ],
        "quaternion": [
          0,
          0.8457331,
          0,
          0.5336061
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0041467
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.3835326,
          0.3388748,
          0.1386787
        ],
        "quaternion": [
          -0.0729638,
          0.735469,
          0.0665013,
          0.6703277
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t90_x",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0059652
      }
    ]
  }
});
