// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "chieftain5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          1.771,
          1.18,
          0
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          -1.771,
          1.18,
          0
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -0.696,
          0.2716974,
          -1.7411999
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "chieftain_mk10": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          1.8215,
          1.17,
          0
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          -1.8215,
          1.17,
          0
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          0.736,
          0.2113302,
          -1.5446999
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain_mk10",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "fv510": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.6527,
          1.3650477,
          -0.6372299
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "fv510",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.242,
        "pos": [
          0.8935218,
          0.2645097,
          -0.1086994
        ],
        "quaternion": [
          -0.0272535,
          0.6251992,
          0.0339688,
          0.7792492
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.001539
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.242,
        "pos": [
          -0.8875693,
          0.2643657,
          -0.1087202
        ],
        "quaternion": [
          -0.0195706,
          -0.6268709,
          -0.0243044,
          0.778498
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.0021707
      }
    ]
  },
  "fv510_milan": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -1.6527,
          1.340416,
          -0.7046599
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "fv510_milan",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.242,
        "pos": [
          0.8935218,
          0.2645097,
          -0.1086994
        ],
        "quaternion": [
          -0.0272535,
          0.6251992,
          0.0339688,
          0.7792492
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0710308
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.242,
        "pos": [
          -0.8875693,
          0.2643657,
          -0.1087202
        ],
        "quaternion": [
          -0.0195706,
          -0.6268709,
          -0.0243044,
          0.778498
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0782471
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.9926152,
          0.33,
          -0.5287183
        ],
        "quaternion": [
          0,
          0.7482354,
          0,
          0.6634334
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0357229
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          -0.9926152,
          0.33,
          -0.5287183
        ],
        "quaternion": [
          0,
          -0.7482354,
          0,
          0.6634334
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0357229
      }
    ]
  },
  "vickers_mk1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.285,
        "pos": [
          1.488948,
          1.2166091,
          -0.665
        ],
        "quaternion": [
          -0.0359369,
          0.706193,
          0.0359369,
          0.706193
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000426
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.285,
        "pos": [
          -1.488948,
          1.2166091,
          -0.665
        ],
        "quaternion": [
          -0.0359369,
          -0.706193,
          -0.0359369,
          0.706193
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.000426
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          1.4913831,
          1.192745,
          0.3747749
        ],
        "quaternion": [
          -0.0359369,
          0.706193,
          0.0359369,
          0.706193
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "vickers_mk1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "centurion3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.471,
          0.3169,
          -0.326
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.5185,
          0.3169,
          0.0425
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "centurion5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.471,
          0.33135,
          -0.6192001
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0022161
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.1909999,
          0.41805,
          -1.2176001
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0048049
      }
    ]
  }
});
