// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Kevin Liu.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

import type { VehicleMarkingSeatRecord } from '../vehicleMarkingSeatRegistry.ts';

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, VehicleMarkingSeatRecord>> = Object.freeze({
  "ua_t64bv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.0136709,
          0.5342663,
          -0.2918975
        ],
        "quaternion": [
          -0.3493046,
          0.657857,
          0.3129125,
          0.5893185
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t64bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.3145129
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          0.5835706,
          0.3495901,
          -1.1927164
        ],
        "quaternion": [
          -0.4296462,
          0.8052569,
          0.1923503,
          0.3605092
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t64bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.6660947
      }
    ]
  },
  "ua_t80bv": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.286,
          1.4066196,
          -1.2653581
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_t80bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.286,
          1.4066196,
          -1.6096552
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_t80bv",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ua_t80u_kursk": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2686408,
          0.2735146,
          -0.4226998
        ],
        "quaternion": [
          0.0386052,
          -0.8505849,
          0.0237771,
          0.5238794
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_kursk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0153404
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4238485,
          0.2735062,
          -0.0474039
        ],
        "quaternion": [
          0.033276,
          -0.7847861,
          0.0262175,
          0.6183172
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t80u_kursk",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 1e-7
      }
    ]
  },
  "ua_t84_oplot_m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.531,
          0.364,
          0.5478
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t84_oplot_m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.0373657,
          0.4846564,
          -1.355184
        ],
        "quaternion": [
          -0.0805562,
          0.8319726,
          0.0529038,
          0.5463822
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "ua_t84_oplot_m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ua_m1a1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          1.738133,
          1.5627299,
          -2.20516
        ],
        "quaternion": [
          -0.0170924,
          0.7069002,
          0.0170924,
          0.7069002
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.2326348
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.27,
        "pos": [
          1.818,
          1.2676,
          -3.30724
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "ua_m1a1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
